# -*- coding: utf-8 -*-
"""ROHITH_IT533

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KbWwkil-p-zQ7pIM1A_AJCJN-pCGojEr
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

adult = pd.read_csv("https://raw.githubusercontent.com/shstreuber/Data-Mining/master/data/kickstarter-projects-201518.csv", encoding="ISO-8859-1")

adult
# adult.head(5)
# adult.tail(7)

adult.describe(include='all')

"""1. structure of dataset
  The dataset contains information the project goal, the outcome project location, the category, when it was created and also some extra information about the creator for a part of the projects. some of the examples are Id,name,category,currency etc..
  It has 191585 rows and 15 columns.
"""

adult.select_dtypes('int')

adult.select_dtypes('float')

adult.select_dtypes('string')

adult.usd_goal_real.describe()

"""2. class attribute.       
  From the given dataset I've taken goal as my class attribute. It mainly depends upon the backers and their Id numbers.
"""

adult.goal.describe()

adult.goal.median()

adult.goal.mode()

"""3.  number summary.    
   number summary is nothing but 
  a) mean
  b) median
  c) standard deviation
  d) min
  e) max
  f) mode
  

  a) mean:- mean is nothing but the average of the dataset. value of mean is 6.80     
  b) median:- median is the middle value of the dataset. value of median is 6500.    
  c) standard deviation:- It is nothing but value of amount of variation or dispersion. value of standard deviation is 1.49                                       
  d) min:- It is nothing but the minimum value. min=1.000000e+00  
  e) max:- It is the maximum value. max=1.000000e+08.  
  f) mode:- mode is nothing but set of data values. 
"""

adult.ID.describe()

adult.backers.describe()

"""5. other numeric attributes.      
  In the above sections we have calculated the 5 number summary and the the results are as followed.  
  For Id the mean is 1.07. min is 1.85 and max is 2.14 and the std is 6.19. For backers the mean value is 112.8. min is 0 and the max is 219382 and the standard deviation is 1018.
"""

adult.boxplot()

"""4. boxplot:-                
   This boxplot is the graphical representation of the class attribute which we have taken that is goal. Here the min,median and the max value is shown in the above plot for the ID attribute.
"""

adult.boxplot(['goal','backers'])

fig1, ax1 = plt.subplots()
ax1.set_title('ID')
ax1.boxplot(adult.ID)

adult.ID.hist()

point1 = np.array((adult.goal))
point2 = np.array((adult.backers))
  
 # Let's check what x and y contain:
print("Array 1:")
print(point1)
  
print("Array 2:")
print(point2)

dist = np.linalg.norm(point1 - point2)
  
# printing Euclidean distance
print("Euclidean distance between goal and backers is:", dist)

"""6. Euclidian distance.      
   Euclidian distance is the length connecting two points in a plane or in a 3 dimensional space.
   Here the euclidian distance is calculated by using the formula √((x2−x1)^2+(y2−y1)^2) and the result is as follows 653059306.47.

7. Results.     
   This dataset is definitely highly interesting and also very relevant. We got quite a lot of information about a huge amount of crowdsourcing data located on Kickstarter.   
I've taken goal as my class attribute and calculated the 5 numeric attributes for that, showing the relationshp between them. The boxplot is also represented for the attributes ID and backers.
"""

point1 = np.array((adult.goal))
point2 = np.array((adult.backers))
  
 # Let's check what x and y contain:
print("Array 1:")
print(point1)
  
print("Array 2:")
print(point2)

dist = np.linalg.norm(point1 - point2)
  
# printing Euclidean distance
print("Euclidean distance between goal and backers is:", dist)

point1 = np.array((adult.pledged))
point2 = np.array((adult.backers))
  
 # Let's check what x and y contain:
print("Array 1:")
print(point1)
  
print("Array 2:")
print(point2)

dist = np.linalg.norm(point1 - point2)
  
# printing Euclidean distance
print("Euclidean distance between pledged and backers is:", dist)